### ISSUE TITLE
Resizing browser size does not resize menu

### ISSUE THREAD

**Issue by j9chan** [rackerlabs/docs-cloud-files#67] opened 2016-05-16 17:34 UTC
1. On https://developer.rackspace.com/docs/cloud-files/v1/developer-guide/#document-getting-started/authenticate
2. Resize width of the browser (I was on Chrome).
<img width="973" alt="screen shot 2016-05-16 at 11 49 18 am" src="https://cloud.githubusercontent.com/assets/9523536/15297917/5e2310ea-1b62-11e6-9924-e0bb783dcb89.png">

**Comment by catlook** [comment] 2016-05-16 17:45
J9chan,   Thanks for bringing this to our attention! We'll dig in, and see what we can do to make the pages behave properly!  Stay tuned for updates :)  -- Cat

**Comment by meker12** [comment] 2016-05-17 21:26
@j9chan  and @catlook  This is a duplicate of another issue: https://github.com/rackerlabs/nexus-control/issues/172. 
I've added this report to that issue.  Follow that issue for updates.  Thanks for reporting the issue.

**Closed by meker12** 2016-05-17 21:26 UTC
